[package]
name = "bmake-engine"
version.workspace = true
edition.workspace = true

[dependencies]
bmake-ast = { path = "../bmake-ast" }
bmake-parser = { path = "../bmake-parser" }
anyhow = "1"
reqwest = { version = "0.12", features = ["blocking", "json"] }
which = "6"
sha2 = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
argon2 = "0.5"
chacha20poly1305 = "0.10"
rand = "0.8"
zeroize = "1"

[dev-dependencies]
tempfile = "3"