pub struct SyntaxEntry {
    pub name: &'static str,
    pub form: &'static str,
    pub purpose: &'static str,
    pub scope: &'static str,
    pub example: &'static str,
    pub related: &'static [&'static str],
    pub since: &'static str,
    pub deprecated: Option<&'static str>,
}

/// One entry per directive/construct actually recognized by
/// `bmake-parser`. If it's not accepted by the real parser, it's not in
/// this list — this reference is generated from what BMake actually does,
/// not aspirational documentation.
pub fn all_entries() -> Vec<SyntaxEntry> {
    vec![
        SyntaxEntry {
            name: "<Version: ...>",
            form: "<Version: 1.0>",
            purpose: "Pins the BMake Engine version this project requires. Resolved from .bmake/engines/<version>/ locally, or downloaded from GitHub Releases if missing. Never auto-upgraded.",
            scope: "Must appear before Start, once per file.",
            example: "<Version: 1.0>",
            related: &["Start / Stop"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Start / Stop",
            form: "Start ... Stop",
            purpose: "Lifecycle markers bounding the configuration body of a .bm file.",
            scope: "Start follows <Version: ...>; Stop ends the file.",
            example: "<Version: 1.0>\n\nStart\n...\nStop",
            related: &["<Version: ...>"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Task",
            form: "<Task: Name> ... </Task>",
            purpose: "Groups Before/After/Command/Depends-on/Condition/etc for one unit of work. The only block-style construct in BMake, per 'flat by default, block only when necessary'.",
            scope: "Inside Start/Stop.",
            example: "<Task: Build>\n    Command: ./gradlew build\n</Task>",
            related: &["Command", "Depends-on", "Condition"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Command",
            form: "Command: <command>",
            purpose: "Runs a command using the Shell that's configured (global or per-Task).",
            scope: "Inside a Task.",
            example: "Command: ./gradlew build\n\nCommand: {\n    ./gradlew +/\n    assembleRelease +/\n    --no-daemon\n}",
            related: &["Shell", "Timeout", "OnError / Retry / Timeout"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Depends-on",
            form: "Depends-on: TaskA, TaskB",
            purpose: "Declares Task dependencies. BMake builds a dependency graph, detects circular dependencies, and runs independent Tasks in parallel when Parallel: true.",
            scope: "Inside a Task.",
            example: "<Task: Package>\n    Depends-on: Compile, Test\n    Command: package\n</Task>",
            related: &["Task", "Cache / Parallel / Profile", "StopOnError"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Condition",
            form: "Condition: Field == Value",
            purpose: "Skips a Task at runtime unless the comparison holds. Field can be Profile, Platform, Arch, Lang, System, or Runs-on.",
            scope: "Inside a Task.",
            example: "Condition: Profile == Release",
            related: &["Cache / Parallel / Profile"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Env",
            form: "Env: NAME=value",
            purpose: "Sets an environment variable for Command execution. Global Env: is inherited by every Task; Task-level Env: overrides it by name.",
            scope: "Global or inside a Task.",
            example: "Env: JAVA_HOME=/opt/jdk17",
            related: &["Command"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Dependency / Need",
            form: "Dependency: JDK\nNeed: openjdk17",
            purpose: "Declares a build dependency BMake should check for and install (sandboxed for apt/pkg, system-wide fallback for brew/dnf/pacman).",
            scope: "Global.",
            example: "Dependency: JDK\nNeed: openjdk17",
            related: &["Tool / Need", "Require"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Tool / Need",
            form: "Tool: Ninja\nNeed: 1.12",
            purpose: "Declares a build tool BMake should check for (and try to install), separate from Dependency — meant for toolchain executables.",
            scope: "Global.",
            example: "Tool: Ninja\nNeed: 1.12",
            related: &["Dependency / Need"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Require",
            form: "Require: Git",
            purpose: "Declares a tool that MUST already be present. Never auto-installed — the build stops with a clear error if missing.",
            scope: "Global.",
            example: "Require: Git",
            related: &["Dependency / Need"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Runs-on / version / Arch",
            form: "Runs-on: ubuntu\nversion: 24.04\nArch: x86_64",
            purpose: "Describes the target execution environment for Remote builds and Runner matching. 'version:' here is the environment version — not the same as the <Version: ...> engine tag.",
            scope: "Global.",
            example: "Runs-on: ubuntu\nversion: 24.04",
            related: &["Remote", "<Version: ...>"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Remote",
            form: "Remote: Local | CI | Auto",
            purpose: "Chooses the execution backend. Local matches a registered Runner (cloud if logged in, else the offline single-machine registry); CI currently falls back to local execution; Auto lets BMake decide.",
            scope: "Global.",
            example: "Remote: Local",
            related: &["Runs-on / version / Arch"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Cache / Parallel / Profile",
            form: "Cache: true\nParallel: true\nProfile: Release",
            purpose: "Cache enables build-tool caching and incremental-build skipping. Parallel lets independent Tasks run concurrently. Profile is a free-form value, often read back via Condition.",
            scope: "Global.",
            example: "Cache: true\nParallel: true\nProfile: Release",
            related: &["Condition", "Depends-on"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Input / Output",
            form: "Input: src/\nOutput: build/classes/",
            purpose: "Declares a Task's inputs and outputs. When both are set, BMake fingerprints Input and skips the Task on the next run if nothing changed and Output still exists.",
            scope: "Inside a Task.",
            example: "Input: src/\nOutput: build/classes/",
            related: &["Cache / Parallel / Profile"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Artifact",
            form: "Artifact: build/app-release.apk",
            purpose: "Marks a build output for reporting (and, for cloud builds, for the website). Supports a trailing '*' wildcard.",
            scope: "Global or inside a Task.",
            example: "Artifact: build/*.apk",
            related: &["Input / Output"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Workdir",
            form: "Workdir: android/",
            purpose: "Sets the working directory for Command execution. Task-level Workdir overrides the global one. 'Directory:' is still accepted as a backward-compatible alias.",
            scope: "Global or inside a Task.",
            example: "Workdir: android/",
            related: &["Command"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "import =",
            form: "import = other.bm",
            purpose: "Merges another .bm file's configuration into this one before the execution graph is built. Circular imports are detected. The only directive that uses '=' instead of ':'.",
            scope: "Global.",
            example: "import = android.bm",
            related: &["Task"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "OnError / Retry / Timeout",
            form: "OnError: stop | retry\nRetry: 3\nTimeout: 300",
            purpose: "Controls what happens when a Command fails: stop the Task, or retry up to Retry times. Timeout (seconds) applies per-command, or as a Task-level default.",
            scope: "Inside a Task, following a Command.",
            example: "Command: download\nOnError: retry\nRetry: 3",
            related: &["Command", "StopOnError"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "StopOnError",
            form: "StopOnError: true | false",
            purpose: "Defaults to true. When a Task fails, Tasks that depend on it are skipped (true) or still attempted (false) — Tasks already running are never killed.",
            scope: "Global.",
            example: "StopOnError: false",
            related: &["Depends-on"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Rename",
            form: "Rename: from -> to",
            purpose: "Renames a build artifact after a Task's Commands finish.",
            scope: "Inside a Task.",
            example: "Rename: build/app-release.apk -> build/MyApp.apk",
            related: &["Command"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Before / After",
            form: "Before: <command>\nAfter: <command>",
            purpose: "Runs a command immediately before or after a Task's main Commands.",
            scope: "Inside a Task.",
            example: "Before: echo Starting build",
            related: &["Command"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Clean",
            form: "Clean: build/",
            purpose: "Declares extra paths 'bmake clean' should remove. Never removes .bmake/engines or .bmake/dependencies, even with --deep.",
            scope: "Global.",
            example: "Clean: build/",
            related: &[],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Log-level",
            form: "Log-level: normal | verbose | debug",
            purpose: "Controls execution detail. Overridable per run with --verbose/--debug. Debug mode redacts values whose key looks like a secret.",
            scope: "Global.",
            example: "Log-level: verbose",
            related: &[],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Comments",
            form: "// single line\n/+ multi\n   line +\\",
            purpose: "Comments are stripped before parsing and never reach the execution engine.",
            scope: "Anywhere.",
            example: "Lang: Kotlin // language project",
            related: &[],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Value:",
            form: "Value:\n    Key: value\n    Group:\n        Nested: value",
            purpose: "Declares arbitrary structured project data (no fixed schema) at global scope. Referenced elsewhere as ${{ Value.Group.Nested }}. Unused leaves are reported as warnings by 'bmake validate'; undefined references stop the build with a clear error.",
            scope: "Global only — never inside a Task.",
            example: "Value:\n    Project:\n        Name: MyApp\n\n<Task: Build>\n    Env: NAME=${{ Value.Project.Name }}\n</Task>",
            related: &["Secret:", "Env"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Secret:",
            form: "Secret: <SecretName>",
            purpose: "Declares that a secret is required (never its value). Referenced as ${{ Secret.Name }}.",
            scope: "Global.",
            example: "Secret: DeployToken",
            related: &["Value:"],
            since: "1.0",
            deprecated: Some("Reference resolution for ${{ Secret.* }} is not implemented yet — declaring one currently only documents intent."),
        },
        SyntaxEntry {
            name: "ContinueOnError",
            form: "ContinueOnError: true | false",
            purpose: "Per-Task override of StopOnError: decides whether Tasks depending on THIS one still run if it fails. Task-level ContinueOnError always takes precedence over the global StopOnError for that Task's own failures.",
            scope: "Inside a Task.",
            example: "<Task: Deploy>\n    ContinueOnError: true\n    Command: ./deploy.sh\n</Task>",
            related: &["StopOnError", "Depends-on"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Secret:",
            form: "Secret: <SecretName>",
            purpose: "Declares that a secret is required (never its value — that's rejected as a plaintext-secret error). Referenced as ${{ Secret.Name }}, resolved from the encrypted secret.bm.locksys vault at runtime and masked in all command output/logs.",
            scope: "Global.",
            example: "Secret: DeployToken\n\n<Task: Deploy>\n    Env: TOKEN=${{ Secret.DeployToken }}\n    Command: ./deploy.sh\n</Task>",
            related: &["Value:"],
            since: "1.0",
            deprecated: None,
        },
        SyntaxEntry {
            name: "Uses:",
            form: "Uses: <flow-path>",
            purpose: "Runs a reusable Plugin Flow — resolved to .bmake/flows/<flow-path>.bm and materialized into a Task with the flow's path as its name, so it goes through the exact same dependency graph, executor, Value/Secret resolution, and CLI output as any other Task. Never wrapped in <Task: ...>.",
            scope: "Global only.",
            example: "Uses: android/build\n\n<Task: Test>\n    Depends-on: android/build\n    Command: ./gradlew test\n</Task>",
            related: &["Depends-on", "Value:", "Secret:"],
            since: "1.0",
            deprecated: None,
        },
    ]
}